-- Videos are routed through Grok/xAI, but existing group pricing is operator
-- configuration. Managed updates must not rewrite it because an image rollback
-- cannot reconstruct the original values. Runtime platform checks decide
-- whether these fields are used; this migration intentionally performs no SQL.
